name: Build and Test Docker Image

on:
  workflow_dispatch:
  pull_request:
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: lowercaseRepo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create short sha and tag
      shell: bash
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Write dummy config
      run: |
        mkdir -p /tmp/config
        echo "detectors:\n\tdeepstack:\n\t\turl: http://localhost:5000" > /tmp/config/config.yml
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .build/Dockerfile
        push: false
        load: true
        tags: |
          doubletake:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: run docker Image
      run: |
        docker run -d --rm -v /tmp/config:/.storage/config -p 3000:3000 doubletake:latest
    - name: Check http status code
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://localhost:3000/api/config", "http://localhost:3000/api/status/auth"]'
        expected: '[200, 200]'